cameras:
- id: 1
  name: puerta
  source: '1'
  type: local
  enabled: true
  show_bbox: true
  detect_classes:
  - 0
  - 2
  motion_detection_enabled: true
  show_motion_contours: false
  motion_sensitivity: 1000
- id: 2
  name: lobby
  source: C:/Users/usuario/Videos/Screen Recordings/lobby.mp4
  type: file
  enabled: true
  show_bbox: true
  detect_classes:
  - 0
  - 2
  motion_detection_enabled: true
  show_motion_contours: false
  motion_sensitivity: 1000
- id: 3
  name: garita
  source: C:/Users/usuario/Videos/Screen Recordings/capilla.mp4
  type: file
  enabled: true
  show_bbox: true
  detect_classes:
  - 0
  - 2
  motion_detection_enabled: true
  show_motion_contours: false
  motion_sensitivity: 1000
sync:
  enabled: true
  endpoint: http://34.144.231.224/api/video-data/analyze-frame
  auth_token: ''
  cameras:
  - puerta
